services:
  - type: web
    name: nvidia-rag-agent
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.server:app --host 0.0.0.0 --port $PORT --limit-max-requests 0 --timeout-keep-alive 120 --limit-concurrency 1000"
    envVars:
      - key: NVIDIA_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
